
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\andre\Desktop\build\assets\frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1569x999")
window.configure(bg = "#131F3E")


canvas = Canvas(
    window,
    bg = "#131F3E",
    height = 999,
    width = 1569,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_rectangle(
    0.0,
    188.0,
    475.0,
    1089.0,
    fill="#638BD8",
    outline="")

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=50.0,
    y=349.0,
    width=21.000015258789062,
    height=21.0
)

canvas.create_text(
    82.0,
    396.0,
    anchor="nw",
    text="Patient",
    fill="#0A0F1A",
    font=("InriaSans Regular", 20 * -1)
)

canvas.create_text(
    77.9459228515625,
    345.53874307498336,
    anchor="nw",
    text="Doctor",
    fill="#0A0F1A",
    font=("InriaSans Regular", 20 * -1)
)

image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    237.0,
    170.0,
    image=image_image_1
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    74.0,
    253.0,
    image=image_image_2
)

image_image_3 = PhotoImage(
    file=relative_to_assets("image_3.png"))
image_3 = canvas.create_image(
    74.0,
    214.0,
    image=image_image_3
)

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    249.0,
    214.0,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#EEF5FF",
    fg="#000716",
    highlightthickness=0
)
entry_1.place(
    x=101.0,
    y=201.0,
    width=296.0,
    height=24.0
)

entry_image_2 = PhotoImage(
    file=relative_to_assets("entry_2.png"))
entry_bg_2 = canvas.create_image(
    249.0,
    253.0,
    image=entry_image_2
)
entry_2 = Entry(
    bd=0,
    bg="#EEF5FF",
    fg="#000716",
    highlightthickness=0
)
entry_2.place(
    x=101.0,
    y=240.0,
    width=296.0,
    height=24.0
)

canvas.create_rectangle(
    749.0,
    337.0,
    867.0,
    454.0,
    fill="#000000",
    outline="")

canvas.create_text(
    139.0,
    26.0,
    anchor="nw",
    text="SanApp",
    fill="#EEF5FF",
    font=("InriaSans Bold", 70 * -1)
)

canvas.create_text(
    14.0,
    277.0,
    anchor="nw",
    text="Select a role ",
    fill="#0A0F1A",
    font=("InriaSans Regular", 20 * -1)
)

image_image_4 = PhotoImage(
    file=relative_to_assets("image_4.png"))
image_4 = canvas.create_image(
    1022.0,
    638.0,
    image=image_image_4
)

image_image_5 = PhotoImage(
    file=relative_to_assets("image_5.png"))
image_5 = canvas.create_image(
    81.0,
    74.0,
    image=image_image_5
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat"
)
button_2.place(
    x=50.0,
    y=395.0,
    width=21.000015258789062,
    height=21.0
)
window.resizable(False, False)
window.mainloop()
